# config.yaml
query: "User has to enter its query"
name: "default_experiment_name"
workflow:
  copilot: True # whether to use copilot mode or not
  scientist_modules: # which modules to use in the scientist workflow, for reasoning models like openai's o3, planing might not be necessary
    plan: False
    reflect: False 
  reflection_max_iters: 5 # how many times the scientist can reflect (the higher is not necessarily better, start from lower values and increase if needed)
  no_retries: 10 # no  of scientist retries till generate the structured output
  no_paper_revise: 0 # no of times the scientist can revise the paper, best to test it with 0, if needed increase it to higher values

llm:
  scientists:
    provider: openai          # one of: openai, grok
    model: gpt-4.1-mini    # model name

  experts:
    provider: openai
    model: gpt-4.1-mini

  mathematician_expert:
    provider: openai
    model: o4-mini
  
  vision_expert:
    provider: openai
    model: gpt-4.1-mini


paths:
  output_dir: where/to/save/outputs
  contact_network_path: optional/path/to/contact_network_file
  data_dir: optional/path/to/data_dir
